repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    #-   id: end-of-file-fixer
    #-   id: trailing-whitespace
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v1.7.0
#    hooks:
#    -   id: autopep8
#-   repo: https://github.com/pycqa/flake8
#    rev: 5.0.4
#    hooks:
#    -   id: flake8
