dist: xenial

services:
  - docker

language: python
python:
  - "3.6"

stages:
  - test

jobs:
  include:
    - stage: test
      install:
        # Build the docker images with docker-compose
        - docker-compose build
      
      script:
        # Run tests via pytest runner with coverage in a docker container
        - docker run -v $PWD:/coverage --rm ocs sh -c "COVERAGE_FILE=/coverage/.coverage.docker python3 -m pytest -p no:wampy --cov /app/ocs/ocs/ ./tests/"

      after_success:
        # Install coveralls
        - pip install coveralls

        # Combine results from suffixed .coverage.docker to fix paths from container testing
        - coverage combine

        # Show report with updated paths
        - coverage report

        # Publish results to coveralls
        - coveralls
