dist: xenial

services:
  - docker

language: python
python:
  - "3.6"

stages:
  - test
  - name: dockerize
    if: |
      branch = master AND \
      type = push

jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements.txt
        - python3 setup.py install
      
      script: pytest -p no:wampy --cov ocs tests/
      
      after_success: coveralls

    - stage: dockerize
      install: true

      before_script:
        # Use the git tag to tag docker image
        - export DOCKER_TAG=`git describe --tags --always`
        # Login to docker
        - echo "${REGISTRY_PASSWORD}" | docker login "${REGISTRY_URL}" -u "${REGISTRY_USER}" --password-stdin;

      script:
        # Build the docker images with docker-compose
        - docker-compose build

      after_success:
        # Tag all images for upload to the registry
        - "docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker tag {}:latest ${REGISTRY_URL}/{}:latest"
        - "docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker tag {}:latest ${REGISTRY_URL}/{}:${DOCKER_TAG}"

        # Upload to docker registry
        - "docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker push ${REGISTRY_URL}/{}:${DOCKER_TAG}"
        - "docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker push ${REGISTRY_URL}/{}:latest"
        - "docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} echo ${REGISTRY_URL}/{}:${DOCKER_TAG} pushed"
